  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?= $_SESSION['usuario']->avatar; ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?= $_SESSION['usuario']->nombre." ".$_SESSION['usuario']->apellidos; ?></p>
        </div>
      </div>
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">PRINCIPAL</li>
        <li class="treeview <?= (isset($silebar) && $silebar == "panel") ? "active menu-open" : ""; ?>">
          <a href="#">
            <i class="fa fa-tachometer-alt"></i> <span>Panel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="<?= (isset($contenido) && $contenido == "Default") ? "active" : ""; ?>"><a href="index.php"><i class="fa fa-circle"></i> Inicio</a></li>
            <li class="<?= (isset($contenido) && $contenido == "Perfil") ? "active" : ""; ?>"><a href="Perfil"><i class="fa fa-circle"></i> Perfil</a></li>
          </ul>
        </li>
        <li class="treeview <?= (isset($silebar) && $silebar == "usuarios") ? "active menu-open" : ""; ?>">
          <a href="#">
            <i class="fa fa-users"></i> <span>Usuarios</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="<?= (isset($contenido) && $contenido == "Usuarios") ? "active" : ""; ?>"><a href="Usuarios"><i class="fa fa-circle"></i> Usuarios</a></li>
            <li class="<?= (isset($contenido) && $contenido == "Grupos") ? "active" : ""; ?>"><a href="Grupos"><i class="fa fa-circle"></i> Grupos</a></li>
          </ul>
        </li>
      </ul>
    </section>
  </aside>