  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        404 Error de página
      </h1>
      <ol class="breadcrumb">
        <li><a href="index.php"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">404 error</li>
      </ol>
    </section>

    <section class="content">
      <div class="error-page">
        <h2 class="headline text-yellow"> 404</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-yellow"></i> Oops! Página no encontrada.</h3>

          <p>
          No hemos podido encontrar la página que estabas buscando. Mientras tanto, puede volver al <a href="index1.php">panel</a>.
          </p>
        </div>
      </div>
    </section>
  </div>