  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Inicio
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Panel</a></li>
        <li class="active">Inicio</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
<div class="row">
  <div class="col-md-12 ">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Ultimas acciones</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div>
          <table id="tabla_log" class="table table-hover tabla-datatable">
            <thead>
              <tr>
                <th>#</th>
                <th>Id Usuario</th>
                <th>Acción</th>
                <th>Fecha</th>
              </tr>
            </thead>
            <tbody>
              <?php
                foreach($logs as $log){
                  ?>
                    <tr>
                      <td><?= $log->id_log; ?></td>
                      <td><?= $log->id_usuario; ?></td>
                      <td><?= $log->accion; ?></td>
                      <td><?= Log::fecha($log->fecha); ?></td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
            <tbody>
              <tr>
                <th>#</th>
                <th>Id Usuario</th>
                <th>Acción</th>
                <th>Fecha</th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</ class="row">
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->