  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Perfil
      </h1>
      <ol class="breadcrumb">
        <li><a href="index1.php"><i class="fa fa-dashboard"></i> Panel</a></li>
        <li class="active">Perfil</li>
      </ol>
    </section>

    <section class="content">

      <div class="row">
        <div class="col-md-3">

          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="<?= $usuario->avatar; ?>" alt="User profile picture">

              <h3 class="profile-username text-center"><?= $usuario->nombre." ".$usuario->apellidos; ?></h3>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Nivel</b> <a class="pull-right">Administrador</a>
                </li>
                <li class="list-group-item">
                  <b>Grupo</b> <a class="pull-right">Administradores</a>
                </li>
              </ul>

            </div>
          </div>
        </div>
        <div class="col-md-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#settings" data-toggle="tab">Ajustes</a></li>
            </ul>
            <div class="tab-content">
              <div class="active tab-pane" id="settings">
                <form method="POST" enctype="multipart/form-data" class="form-horizontal">
                <input type="hidden" name="id_usuario" value="<?= $usuario->id_usuario; ?>" />
                <input type="hidden" name="ajustes" />
                  <div class="form-group">
                    <label class="col-sm-2 control-label">Nombre</label>

                    <div class="col-sm-10">
                      <input type="text" class="form-control" name="nombre" value="<?= $usuario->nombre; ?>" placeholder="Nombre" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label">Apellidos</label>

                    <div class="col-sm-10">
                      <input type="text" class="form-control" name="apellidos" value="<?= $usuario->apellidos; ?>" placeholder="Apellidos" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label">Correo</label>

                    <div class="col-sm-10">
                      <input type="email" class="form-control" name="correo" value="<?= $usuario->correo; ?>" placeholder="Correo" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label">Usuario</label>

                    <div class="col-sm-10">
                      <input type="text" class="form-control" name="usuario" value="<?= $usuario->usuario; ?>" placeholder="Usuario" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label">Avatar</label>

                    <div class="col-sm-10">
                      <input type="file" class="form-control" name="avatar">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">Guardar</button>
                      <a  href="#" class="btn btn-warning" data-izimodal-open="#cambiar_password" data-izimodal-transitionin="fadeInDown">Cambiar contraseña</a>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

    </section>
  </div>

  <!-- MODALES -->

  <div id="cambiar_password" data-izimodal-fullscreen="true" data-izimodal-title="Cambio de contraseña" data-izimodal-icon="icon-home" aria-hidden="false" aria-labelledby="modal-default" role="dialog" class="iziModal" data-izimodal-loop="true" >
  <div class="container-fluid" style="margin-top: 10px; margin-bottom: 10px;">
    <form method="POST">
    <input type="hidden" name="id_usuario" value="<?= $usuario->id_usuario; ?>" />
    <input type="hidden" name="cambio_password" />
      <div class="form-group">
        <label>Nueva contraseña</label>
        <input type="text" class="form-control" name="password" placeholder="Contraseña" />
      </div>
      <div class="form-group">
        <label>Repita contraseña</label>
        <input type="text" class="form-control" name="password_repetida" placeholder="Repita Contraseña" />
      </div>
      <input type="submit" class="btn btn-primary" value="Guardar" />
    </form>
  </div>
</div>