  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuarios
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Productos</a></li>
        <li class="active">Productos</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
<div class="row">
  <div class="col-md-12 ">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title"><button class="btn btn-primary">Nuevo Producto</button></h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div id="caja_productos">
        <table id="tabla_productos" class="table table-hover tabla-datatable">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th>Codigo</th>
                    <th>Descripcion</th>
                    <th>Imagen</th>
                    <th>Stock</th>
                    <th>Precio Compra</th>
                    <th>Precio Venta</th>
                    <th>Ventas</th>
                    <th>Fecha</th>
                    <th></th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th>Codigo</th>
                    <th>Descripcion</th>
                    <th>Imagen</th>
                    <th>Stock</th>
                    <th>Precio Compra</th>
                    <th>Precio Venta</th>
                    <th>Ventas</th>
                    <th>Fecha</th>
                    <th></th>
                </tr>
                </tfoot>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- MODALES -->

  <div id="editar_usuario" data-izimodal-fullscreen="true" data-izimodal-title="Cambio de contraseña" data-izimodal-icon="icon-home" aria-hidden="false" aria-labelledby="modal-default" role="dialog" class="iziModal" data-izimodal-loop="true" >
  <div class="container-fluid" style="margin-top: 10px; margin-bottom: 10px;">
    <form method="POST" name="editar_usuario">
    <input type="hidden" name="id_usuario" />
    <input type="hidden" name="editar_usuario" />
      <div class="form-group">
        <label>Nombre</label>
        <input type="text" class="form-control" name="nombre" placeholder="Nombre" required />
      </div>
      <div class="form-group">
        <label>Apellidos</label>
        <input type="text" class="form-control" name="apellidos"" placeholder="Apellidos" required />
      </div>
      <div class="form-group">
        <label>Correo</label>
        <input type="email" class="form-control" name="correo" placeholder="Correo" required />
      </div>
      <div class="form-group">
        <label>Usuario</label>
        <input type="text" class="form-control" name="usuario" placeholder="Usuario" required />
      </div>
      <input type="button" class="btn btn-primary" value="Guardar" onclick="guardar()" />
      <a href="#" class="btn btn-link" data-izimodal-open="#editar_pass" data-izimodal-transitionin="fadeInDown">Cambiar contraseña</i></a>
    </form>
  </div>
</div>

<script src="JS/productos.js"></script>
