  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuarios
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuarios</a></li>
        <li class="active">Usuarios</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
<div class="row">
  <div class="col-md-12 ">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Usuarios</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div>
          <table id="tabla_usuarios" class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Correo</th>
                <th>Nombre</th>
                <th>Fecha</th>
                <th>Accion</th>
              </tr>
            </thead>
            <tbody>
              <?php
                foreach($usuarios as $usuario){
                  ?>
                    <tr>
                      <td><?= $usuario->id_usuario; ?></td>
                      <td><?= $usuario->usuario; ?></td>
                      <td><?= $usuario->correo; ?></td>
                      <td><?= $usuario->nombre." ".$usuario->apellidos; ?></td>
                      <td><?= Usuario::fecha($usuario->fecha_registro); ?></td>
                      <td>
                        <form style="display: inline;" method="POST">
                          <input type="hidden" name="ide_usuario" value="<?= $usuario->id_usuario; ?>" />
                          <input type="hidden" name="ide_usuario" value="editar" />
                          <button class="btn btn-link" type="submit"><i class="far fa-edit"></i></button>
                        </form>
                        <form style="display: inline;" method="POST">
                          <input type="hidden" name="ide_usuario" value="<?= $usuario->id_usuario; ?>" />
                          <input type="hidden" name="ide_usuario" value="eliminar" />
                          <button class="btn btn-link" type="submit"><i class="far fa-trash-alt"></i></button>
                        </form>
                      </td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
            <tbody>
              <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Correo</th>
                <th>Nombre</th>
                <th>Fecha</th>
                <th>Accion</th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</ class="row">
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



<script>
    $('#tabla_usuarios').DataTable({
        "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
        },
        'order': [[0, 'desc']]
    });
</script>