  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuarios
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuarios</a></li>
        <li class="active">Usuarios</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
<div class="row">
  <div class="col-md-12 ">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Usuarios</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div id="caja_usuarios">
        <table id="tabla_usuarios" class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Usuario</th>
                    <th>Correo</th>
                    <th>Nombre</th>
                    <th>Fecha</th>
                    <th><center><button class="btn btn-primary">Nuevo Usuario</button></center></th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Usuario</th>
                    <th>Correo</th>
                    <th>Nombre</th>
                    <th>Fecha</th>
                </tr>
                </tfoot>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
</ class="row">
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- MODALES -->

  <div id="editar_usuario" data-izimodal-fullscreen="true" data-izimodal-title="Cambio de contraseña" data-izimodal-icon="icon-home" aria-hidden="false" aria-labelledby="modal-default" role="dialog" class="iziModal" data-izimodal-loop="true" >
  <div class="container-fluid" style="margin-top: 10px; margin-bottom: 10px;">
    <form method="POST" name="editar_usuario">
    <input type="hidden" name="id_usuario" />
    <input type="hidden" name="editar_usuario" />
      <div class="form-group">
        <label>Nombre</label>
        <input type="text" class="form-control" name="nombre" placeholder="Nombre" required />
      </div>
      <div class="form-group">
        <label>Apellidos</label>
        <input type="text" class="form-control" name="apellidos"" placeholder="Apellidos" required />
      </div>
      <div class="form-group">
        <label>Correo</label>
        <input type="email" class="form-control" name="correo" placeholder="Correo" required />
      </div>
      <div class="form-group">
        <label>Usuario</label>
        <input type="text" class="form-control" name="usuario" placeholder="Usuario" required />
      </div>
      <input type="button" class="btn btn-primary" value="Guardar" onclick="guardar()" />
      <a href="#" class="btn btn-link" data-izimodal-open="#editar_pass" data-izimodal-transitionin="fadeInDown">Cambiar contraseña</i></a>
    </form>
  </div>
</div>

<div id="editar_pass" data-izimodal-fullscreen="true" data-izimodal-title="Cambio de contraseña" data-izimodal-icon="icon-home" aria-hidden="false" aria-labelledby="modal-default" role="dialog" class="iziModal" data-izimodal-loop="true" >
<div class="container-fluid" style="margin-top: 10px; margin-bottom: 10px;">
  <form method="POST">
  <input type="hidden" name="id_usuario" />
  <input type="hidden" name="editar_pass" />
    <div class="form-group">
      <label>Nueva contraseña</label>
      <input type="text" class="form-control" name="password" placeholder="Contraseña" required />
    </div>
    <div class="form-group">
      <label>Repita contraseña</label>
      <input type="text" class="form-control" name="password_repetida" placeholder="Repita Contraseña" required />
    </div>
    <input type="submit" class="btn btn-primary" value="Guardar" />
  </form>
</div>
</div>



<script>
$(document).ready(function() {
  var table = $('#tabla_usuarios').DataTable( {
      "processing": true,
      "ajax": {
          "url": "AJAX/usuariosAjax.php",
          "type": "POST",
          "data": function (e) {
                e.ver_usuarios = "";
            }
      },
    "columns": [
      { "data": "id_usuario" },
      { "data": "usuario" },
      { "data": "correo" },
      { "data": "nombre" },
      { "data": "fecha_registro" },
      { "data": null }
    ],
      "columnDefs": [
      {
        "targets": -1,
        "defaultContent": "<a href='#' class='btn btn-link editar' data-izimodal-open='#editar_usuario' data-izimodal-transitionin='fadeInDown'><i class='far fa-edit'></i></a><button class='btn btn-link borrar'><i class='far fa-trash-alt'></i></button>"
      },
      {
      "targets": 5, // your case first column
      "className": "text-center",
      "orderable": false,
      "searchable": false
      }
    ]
  });
  $('#tabla_usuarios tbody').on( 'click', 'a.editar', function () {
      var data = table.row( $(this).parents('tr') ).data();
      ver_usuario(data.id_usuario);
  });
  $('#tabla_usuarios tbody').on( 'click', 'button.borrar', function () {
      var data = table.row( $(this).parents('tr') ).data();
      alert(data.usuario);
  });

  $("#editar_usuario").iziModal();
  $("#editar_pass").iziModal();
});

function ver_usuario(id_usuario){
  $.ajax({
    url: "AJAX/usuariosAjax.php",
    method: "POST",
    async: true,
    data: {"ver_usuario" : "", "id" : id_usuario},
    dataType: "json",
    success: function(respuesta) {
      $("form[name=editar_usuario] input[name=id_usuario]").val(respuesta.datos.id_usuario);
      $("form[name=editar_usuario] input[name=nombre]").val(respuesta.datos.nombre);
      $("form[name=editar_usuario] input[name=apellidos]").val(respuesta.datos.apellidos);
      $("form[name=editar_usuario] input[name=correo]").val(respuesta.datos.correo);
      $("form[name=editar_usuario] input[name=usuario]").val(respuesta.datos.usuario);
    }
  });
}

function guardar(){
  $.ajax({
    url: "AJAX/usuariosAjax.php",
    method: "POST",
    async: true,
    data: $("form[name=editar_usuario]").serialize(),
    success: function() {
    $("#editar_usuario").iziModal('close');
      swal({
        position: '',
        type: 'success',
        title: 'Datos guardados correctamente',
        showConfirmButton: false,
        timer: 1500
      });
    }
  });
}
</script>
