  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuarios
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuarios</a></li>
        <li class="active">Usuarios</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
<div class="row">
  <div class="col-md-12 ">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Usuarios</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div>
          <table id="tabla_usuarios" class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Correo</th>
                <th>Nombre</th>
                <th>Fecha</th>
                <th><button class="btn btn-primary">Nuevo Usuario</button></th>
              </tr>
            </thead>
            <tbody>
              <?php
                foreach($usuarios as $usuario){
                  ?>
                    <tr>
                      <td><?= $usuario->id_usuario; ?></td>
                      <td><?= $usuario->usuario; ?></td>
                      <td><?= $usuario->correo; ?></td>
                      <td><?= $usuario->nombre." ".$usuario->apellidos; ?></td>
                      <td><?= Usuario::fecha($usuario->fecha_registro); ?></td>
                      <td>
                        <a href="#" class="btn btn-link" data-izimodal-open="#editar_usuario" data-izimodal-transitionin="fadeInDown"><i class="far fa-edit"></i></a>
                        <form style="display: inline;" method="POST">
                          <input type="hidden" name="id_usuario" value="<?= $usuario->id_usuario; ?>" />
                          <input type="hidden" name="eliminar" />
                          <button class="btn btn-link" type="submit"><i class="far fa-trash-alt"></i></button>
                        </form>
                      </td>
                    </tr>
                  <?php
                }
              ?>
            </tbody>
            <tbody>
              <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Correo</th>
                <th>Nombre</th>
                <th>Fecha</th>
                <th>Accion</th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</ class="row">
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- MODALES -->

  <div id="editar_usuario" data-izimodal-fullscreen="true" data-izimodal-title="Cambio de contraseña" data-izimodal-icon="icon-home" aria-hidden="false" aria-labelledby="modal-default" role="dialog" class="iziModal" data-izimodal-loop="true" >
  <div class="container-fluid" style="margin-top: 10px; margin-bottom: 10px;">
    <form method="POST">
    <input type="hidden" name="id_usuario" value="<?= $usuario->id_usuario; ?>" />
    <input type="hidden" name="editar " />
      <div class="form-group">
        <label>Nueva contraseña</label>
        <input type="text" class="form-control" name="password" placeholder="Contraseña" />
      </div>
      <div class="form-group">
        <label>Repita contraseña</label>
        <input type="text" class="form-control" name="password_repetida" placeholder="Repita Contraseña" />
      </div>
      <input type="submit" class="btn btn-primary" value="Guardar" />
    </form>
  </div>
</div>



<script>
  $(document).ready(function () {
    $('#tabla_usuarios').DataTable({
        "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
        },
        'order': [[0, 'desc']]
    });
    $("#editar_usuario").iziModal();
  })
</script>